default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: iot_db
  username: iot_user
  password: iot_password
  host: localhost
  port: 5432

test:
  <<: *default
  database: iot_db_test
  username: iot_user
  password: iot_password
  host: localhost
  port: 5432

production:
  <<: *default
  database: iot_db_production
  username: iot_user
  password: <%= ENV['IOT_DB_PASSWORD'] %>
  host: localhost
  port: 5432
